language: python
dist: bionic
python:
- '3.6'
- '3.7.13'
- '3.8.13'
- '3.9'
- '3.10.1'
install:
- pip install -U -r requirements.txt
- pip install -U -r test_requirements.txt
- pip install --no-deps -e .
script:
- pytest --cov=gemd --cov-report term-missing:skip-covered --cov-config=tox.ini --no-cov-on-fail --cov-fail-under=100 gemd
- flake8 gemd
- cd docs; make html; cd ..;
- touch ./docs/_build/html/.nojekyll
- if [ "$TRAVIS_PULL_REQUEST" != "false" ] && [ "$TRAVIS_BRANCH" == "main" ]; then bash ./scripts/validate-version-bump.sh; fi
deploy:
  - provider: pages
    skip_cleanup: true
    github_token: "$GH_SECRET_TOKEN"
    keep_history: true
    local_dir: "./docs/_build/html/"
    on:
      tags: true
      python: '3.6' # only need this to run once
  - provider: pypi
    user: "CitrineInformatics"
    password: "$PYPI_PASSWORD"
    distributions: "sdist bdist_wheel"
    skip_existing: true
    on:
      tags: true
