language: python
python:
- '3.5'
- '3.6'
install:
- pip install -U -r requirements.txt
- pip install -U -r test_requirements.txt
- pip install --no-deps -e .
script:
- pytest --flake8 --cov=taurus --cov-report term-missing --cov-report term:skip-covered
  --cov-fail-under=90 -s -r ./taurus
- cd docs; make html; cd ..;
- touch ./docs/_build/html/.nojekyll
deploy:
  provider: pages
  skip_cleanup: true
  github_token: "$GH_SECRET_TOKEN"
  keep_history: true
  local_dir: "./docs/_build/html/"
  on:
    branch: docs/bounds
env:
  global:
    secure: EShDEfEJhStL9RJNZG5eKDNYhH8s7TtiS2rnm/lFikjDjXyL1nuyjtvc7TCGW/tHCRk0/kvFCoQhgDUZeqrDkqQhK9johy9gNhqp/C6TbLxBvVYw8pxOYB9ljpw98WewChjqKOlNBNLhEFXiFWCpTkDX0sC8stSNpxTcxe4atWI+xVbMxnrzf8DfILuyCcnDzCZOcWkVNtZxoiia3JLqwFJH6f5FYL6j3+5GTDE+wPlH/k1G9CSY76tfQQh8D5LoXRhq3anck/sN3ftKe5ZR9Iq2o7HRxK8q2w8UFlvMKmTPu/gR/GHldZgTaeAV5hd6gA2utMjyNp6Or0xngLFbSFJmdg7EvMLOJNKryHnYelBBM29sU6UHxrZUTec0mG+1f79wbVbz9pPNj5Hu7Vwl4mDgrzPzRIc1h0G2+GqBN3+1swjw1xjNtia8E5Thftw7jCjQYsLuX/S83z/2T3RPFtA7oLYRwIDCdkPfH0SKod+fFU5F2q1E7678uc/7WrkQ2IK9KnfoORoDKCNRR3xuZy7WvKzM+lFJxWqo11E/RwpRAJeKOWP13JtTnywIWUkVjPoaZ3cE0xQuEZ1t939ia8kPaabnVzviTA3V+vo8xdCuhFldy69oGCqQZTp7Z1LqXE62V88rthBZiYWDyjskxh64Y1MfrFwNR+gjtcAb8cs=
