name: 'Initialize'
description: 'Checkout repo and install dependencies'
inputs:
  latest:
    description: 'If true, ignore requirements.txt and the versions pinned there.'
    default: 'false'
  documentation:
    description: 'If true, install documentation build frameworks.'
    default: 'false'
runs:
  using: "composite"
  steps:
    - name: Check out repository code
      uses: actions/checkout@v4
    - name: Upgrade pip
      run: python -m pip install --upgrade pip
      shell: bash
    - name: Install minimum-version runtime dependencies + GEMD
      run: python -m pip install --only-binary ':all:' -r requirements.txt
      shell: bash
      if: ${{ inputs.latest == 'false' }}
    - name: Install test dependencies
      run: python -m pip install --only-binary ':all:' -r test_requirements.txt
      shell: bash
    - name: Install documentation building framework
      run: python -m pip install --only-binary ':all:' -r doc_requirements.txt
      shell: bash
      if: ${{ inputs.documentation == 'true' }}
    - name: Install gemd-python, along with the latest version of any outstanding dependencies
      run: python -m pip install --only-binary ':all:' -e .
      shell: bash
